// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using casefile.data.configuration;

#nullable disable

namespace casefile.data.Migrations
{
    [DbContext(typeof(CaseFileContext))]
    [Migration("20260210205455_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("casefile.domain.model.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<Guid?>("SchemaClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_client_id");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<Guid?>("TemplateDossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_dossier_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_email");

                    b.HasIndex("SchemaClientId")
                        .HasDatabaseName("ix_clients_schema_client_id");

                    b.HasIndex("TemplateDossierId")
                        .HasDatabaseName("ix_clients_template_dossier_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.CourrielEnvoye", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("a");

                    b.Property<Guid?>("DossierClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_client_id");

                    b.Property<DateTime>("EnvoyeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("envoye_le");

                    b.Property<string>("PiecesJointes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pieces_jointes");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sujet");

                    b.HasKey("Id")
                        .HasName("pk_courriels_envoyes");

                    b.HasIndex("DossierClientId")
                        .HasDatabaseName("ix_courriels_envoyes_dossier_client_id");

                    b.ToTable("courriels_envoyes", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.DefinitionAttribut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cle");

                    b.Property<bool>("EstRequis")
                        .HasColumnType("boolean")
                        .HasColumnName("est_requis");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("libelle");

                    b.Property<Guid?>("SchemaClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_client_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("ValeurDefaut")
                        .HasColumnType("text")
                        .HasColumnName("valeur_defaut");

                    b.HasKey("Id")
                        .HasName("pk_definitions_attributs");

                    b.HasIndex("Cle")
                        .HasDatabaseName("ix_definitions_attributs_cle");

                    b.HasIndex("SchemaClientId")
                        .HasDatabaseName("ix_definitions_attributs_schema_client_id");

                    b.ToTable("definitions_attributs", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.DocumentAttendu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdTypeDocument")
                        .HasColumnType("uuid")
                        .HasColumnName("id_type_document");

                    b.Property<Guid?>("TemplateDossierElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_dossier_element_id");

                    b.HasKey("Id")
                        .HasName("pk_documents_attendus");

                    b.HasIndex("IdTypeDocument")
                        .HasDatabaseName("ix_documents_attendus_id_type_document");

                    b.HasIndex("TemplateDossierElementId")
                        .HasDatabaseName("ix_documents_attendus_template_dossier_element_id");

                    b.ToTable("documents_attendus", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.DocumentClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AjouteLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ajoute_le");

                    b.Property<string>("CheminPhysique")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chemin_physique");

                    b.Property<Guid?>("DossierClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_client_id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<string>("NomOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_original");

                    b.Property<string>("NomStandardise")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_standardise");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_document_id");

                    b.HasKey("Id")
                        .HasName("pk_documents_clients");

                    b.HasIndex("DossierClientId")
                        .HasDatabaseName("ix_documents_clients_dossier_client_id");

                    b.HasIndex("TypeDocumentId")
                        .HasDatabaseName("ix_documents_clients_type_document_id");

                    b.ToTable("documents_clients", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.DossierClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheminVirtuel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chemin_virtuel");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_dossiers_clients");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_dossiers_clients_client_id");

                    b.ToTable("dossiers_clients", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.ProfilEntreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Signature")
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("pk_profils_entreprise");

                    b.ToTable("profils_entreprise", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.RegleNommageDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.HasKey("Id")
                        .HasName("pk_regles_nommage_documents");

                    b.ToTable("regles_nommage_documents", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.SchemaClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_schemas_clients");

                    b.ToTable("schemas_clients", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.TemplateCourriel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corps");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<Guid?>("ProfilEntrepriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("profil_entreprise_id");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sujet");

                    b.Property<Guid?>("TemplateDossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_dossier_id");

                    b.HasKey("Id")
                        .HasName("pk_templates_courriel");

                    b.HasIndex("ProfilEntrepriseId")
                        .HasDatabaseName("ix_templates_courriel_profil_entreprise_id");

                    b.HasIndex("TemplateDossierId")
                        .HasDatabaseName("ix_templates_courriel_template_dossier_id");

                    b.ToTable("templates_courriel", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_templates_dossier");

                    b.ToTable("templates_dossier", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossierElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdParent")
                        .HasColumnType("uuid")
                        .HasColumnName("id_parent");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<Guid?>("TemplateDossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_dossier_id");

                    b.HasKey("Id")
                        .HasName("pk_templates_dossier_elements");

                    b.HasIndex("IdParent")
                        .HasDatabaseName("ix_templates_dossier_elements_id_parent");

                    b.HasIndex("TemplateDossierId")
                        .HasDatabaseName("ix_templates_dossier_elements_template_dossier_id");

                    b.ToTable("templates_dossier_elements", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.TypeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("DossierCibleParDefaut")
                        .HasColumnType("text")
                        .HasColumnName("dossier_cible_par_defaut");

                    b.Property<string>("ExtensionsPermises")
                        .HasColumnType("text")
                        .HasColumnName("extensions_permises");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<Guid?>("RegleNommageDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("regle_nommage_document_id");

                    b.HasKey("Id")
                        .HasName("pk_types_document");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_types_document_code");

                    b.HasIndex("RegleNommageDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_types_document_regle_nommage_document_id");

                    b.ToTable("types_document", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.ValeurAttributClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cle");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valeur");

                    b.HasKey("Id")
                        .HasName("pk_valeurs_attributs_clients");

                    b.HasIndex("Cle")
                        .HasDatabaseName("ix_valeurs_attributs_clients_cle");

                    b.HasIndex("ClientId", "Cle")
                        .IsUnique()
                        .HasDatabaseName("ix_valeurs_attributs_clients_client_id_cle");

                    b.ToTable("valeurs_attributs_clients", (string)null);
                });

            modelBuilder.Entity("casefile.domain.model.Client", b =>
                {
                    b.HasOne("casefile.domain.model.SchemaClient", "SchemaClient")
                        .WithMany()
                        .HasForeignKey("SchemaClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clients_schemas_clients_schema_client_id");

                    b.HasOne("casefile.domain.model.TemplateDossier", "TemplateDossier")
                        .WithMany()
                        .HasForeignKey("TemplateDossierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clients_templates_dossier_template_dossier_id");

                    b.Navigation("SchemaClient");

                    b.Navigation("TemplateDossier");
                });

            modelBuilder.Entity("casefile.domain.model.CourrielEnvoye", b =>
                {
                    b.HasOne("casefile.domain.model.DossierClient", null)
                        .WithMany("Courriels")
                        .HasForeignKey("DossierClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_courriels_envoyes_dossiers_clients_dossier_client_id");
                });

            modelBuilder.Entity("casefile.domain.model.DefinitionAttribut", b =>
                {
                    b.HasOne("casefile.domain.model.SchemaClient", null)
                        .WithMany("Definitions")
                        .HasForeignKey("SchemaClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_definitions_attributs_schemas_clients_schema_client_id");
                });

            modelBuilder.Entity("casefile.domain.model.DocumentAttendu", b =>
                {
                    b.HasOne("casefile.domain.model.TypeDocument", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("IdTypeDocument")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_attendus_types_document_id_type_document");

                    b.HasOne("casefile.domain.model.TemplateDossierElement", null)
                        .WithMany("DocumentsAttendus")
                        .HasForeignKey("TemplateDossierElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_attendus_templates_dossier_elements_template_doss");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("casefile.domain.model.DocumentClient", b =>
                {
                    b.HasOne("casefile.domain.model.DossierClient", null)
                        .WithMany("Documents")
                        .HasForeignKey("DossierClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_clients_dossiers_clients_dossier_client_id");

                    b.HasOne("casefile.domain.model.TypeDocument", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_clients_types_document_type_document_id");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("casefile.domain.model.DossierClient", b =>
                {
                    b.HasOne("casefile.domain.model.Client", null)
                        .WithMany("Dossiers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_dossiers_clients_clients_client_id");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateCourriel", b =>
                {
                    b.HasOne("casefile.domain.model.ProfilEntreprise", null)
                        .WithMany("TemplatesCourriel")
                        .HasForeignKey("ProfilEntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_templates_courriel_profils_entreprise_profil_entreprise_id");

                    b.HasOne("casefile.domain.model.TemplateDossier", "TemplateDossier")
                        .WithMany()
                        .HasForeignKey("TemplateDossierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_templates_courriel_templates_dossier_template_dossier_id");

                    b.Navigation("TemplateDossier");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossierElement", b =>
                {
                    b.HasOne("casefile.domain.model.TemplateDossierElement", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_templates_dossier_elements_templates_dossier_elements_id_pa");

                    b.HasOne("casefile.domain.model.TemplateDossier", null)
                        .WithMany("Elements")
                        .HasForeignKey("TemplateDossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_templates_dossier_elements_templates_dossier_template_dossi");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("casefile.domain.model.TypeDocument", b =>
                {
                    b.HasOne("casefile.domain.model.RegleNommageDocument", "RegleNommage")
                        .WithOne()
                        .HasForeignKey("casefile.domain.model.TypeDocument", "RegleNommageDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_types_document_regles_nommage_documents_regle_nommage_docum");

                    b.Navigation("RegleNommage");
                });

            modelBuilder.Entity("casefile.domain.model.ValeurAttributClient", b =>
                {
                    b.HasOne("casefile.domain.model.Client", null)
                        .WithMany("ValeursAttributs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_valeurs_attributs_clients_clients_client_id");
                });

            modelBuilder.Entity("casefile.domain.model.Client", b =>
                {
                    b.Navigation("Dossiers");

                    b.Navigation("ValeursAttributs");
                });

            modelBuilder.Entity("casefile.domain.model.DossierClient", b =>
                {
                    b.Navigation("Courriels");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("casefile.domain.model.ProfilEntreprise", b =>
                {
                    b.Navigation("TemplatesCourriel");
                });

            modelBuilder.Entity("casefile.domain.model.SchemaClient", b =>
                {
                    b.Navigation("Definitions");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossier", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossierElement", b =>
                {
                    b.Navigation("DocumentsAttendus");

                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
