// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using casefile.data.configuration;

#nullable disable

namespace casefile.data.Migrations
{
    [DbContext(typeof(CaseFileContext))]
    partial class CaseFileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("casefile.domain.model.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SchemaClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateDossierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchemaClientId");

                    b.HasIndex("TemplateDossierId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("casefile.domain.model.CourrielEnvoye", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DossierClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnvoyeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PiecesJointes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DossierClientId");

                    b.ToTable("CourrielsEnvoyes");
                });

            modelBuilder.Entity("casefile.domain.model.DefinitionAttribut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstRequis")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SchemaClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("ValeurDefaut")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cle");

                    b.HasIndex("SchemaClientId");

                    b.ToTable("DefinitionsAttributs");
                });

            modelBuilder.Entity("casefile.domain.model.DocumentAttendu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTypeDocument")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplateDossierElementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdTypeDocument");

                    b.HasIndex("TemplateDossierElementId");

                    b.ToTable("DocumentsAttendus");
                });

            modelBuilder.Entity("casefile.domain.model.DocumentClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AjouteLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheminPhysique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DossierClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomStandardise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DossierClientId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("DocumentsClients");
                });

            modelBuilder.Entity("casefile.domain.model.DossierClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminVirtuel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("DossiersClients");
                });

            modelBuilder.Entity("casefile.domain.model.ProfilEntreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProfilsEntreprise");
                });

            modelBuilder.Entity("casefile.domain.model.RegleNommageDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReglesNommageDocuments");
                });

            modelBuilder.Entity("casefile.domain.model.SchemaClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SchemasClients");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateCourriel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfilEntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateDossierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfilEntrepriseId");

                    b.HasIndex("TemplateDossierId");

                    b.ToTable("TemplatesCourriel");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TemplatesDossier");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossierElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdParent")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateDossierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdParent");

                    b.HasIndex("TemplateDossierId");

                    b.ToTable("TemplatesDossierElements");
                });

            modelBuilder.Entity("casefile.domain.model.TypeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DossierCibleParDefaut")
                        .HasColumnType("text");

                    b.Property<string>("ExtensionsPermises")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RegleNommageDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RegleNommageDocumentId")
                        .IsUnique();

                    b.ToTable("TypesDocument");
                });

            modelBuilder.Entity("casefile.domain.model.ValeurAttributClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cle");

                    b.HasIndex("ClientId", "Cle")
                        .IsUnique();

                    b.ToTable("ValeursAttributsClients");
                });

            modelBuilder.Entity("casefile.domain.model.Client", b =>
                {
                    b.HasOne("casefile.domain.model.SchemaClient", "SchemaClient")
                        .WithMany()
                        .HasForeignKey("SchemaClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("casefile.domain.model.TemplateDossier", "TemplateDossier")
                        .WithMany()
                        .HasForeignKey("TemplateDossierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SchemaClient");

                    b.Navigation("TemplateDossier");
                });

            modelBuilder.Entity("casefile.domain.model.CourrielEnvoye", b =>
                {
                    b.HasOne("casefile.domain.model.DossierClient", null)
                        .WithMany("Courriels")
                        .HasForeignKey("DossierClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("casefile.domain.model.DefinitionAttribut", b =>
                {
                    b.HasOne("casefile.domain.model.SchemaClient", null)
                        .WithMany("Definitions")
                        .HasForeignKey("SchemaClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("casefile.domain.model.DocumentAttendu", b =>
                {
                    b.HasOne("casefile.domain.model.TypeDocument", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("IdTypeDocument")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("casefile.domain.model.TemplateDossierElement", null)
                        .WithMany("DocumentsAttendus")
                        .HasForeignKey("TemplateDossierElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("casefile.domain.model.DocumentClient", b =>
                {
                    b.HasOne("casefile.domain.model.DossierClient", null)
                        .WithMany("Documents")
                        .HasForeignKey("DossierClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("casefile.domain.model.TypeDocument", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("casefile.domain.model.DossierClient", b =>
                {
                    b.HasOne("casefile.domain.model.Client", null)
                        .WithMany("Dossiers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("casefile.domain.model.TemplateCourriel", b =>
                {
                    b.HasOne("casefile.domain.model.ProfilEntreprise", null)
                        .WithMany("TemplatesCourriel")
                        .HasForeignKey("ProfilEntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("casefile.domain.model.TemplateDossier", "TemplateDossier")
                        .WithMany()
                        .HasForeignKey("TemplateDossierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TemplateDossier");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossierElement", b =>
                {
                    b.HasOne("casefile.domain.model.TemplateDossierElement", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("casefile.domain.model.TemplateDossier", null)
                        .WithMany("Elements")
                        .HasForeignKey("TemplateDossierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("casefile.domain.model.TypeDocument", b =>
                {
                    b.HasOne("casefile.domain.model.RegleNommageDocument", "RegleNommage")
                        .WithOne()
                        .HasForeignKey("casefile.domain.model.TypeDocument", "RegleNommageDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RegleNommage");
                });

            modelBuilder.Entity("casefile.domain.model.ValeurAttributClient", b =>
                {
                    b.HasOne("casefile.domain.model.Client", null)
                        .WithMany("ValeursAttributs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("casefile.domain.model.Client", b =>
                {
                    b.Navigation("Dossiers");

                    b.Navigation("ValeursAttributs");
                });

            modelBuilder.Entity("casefile.domain.model.DossierClient", b =>
                {
                    b.Navigation("Courriels");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("casefile.domain.model.ProfilEntreprise", b =>
                {
                    b.Navigation("TemplatesCourriel");
                });

            modelBuilder.Entity("casefile.domain.model.SchemaClient", b =>
                {
                    b.Navigation("Definitions");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossier", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("casefile.domain.model.TemplateDossierElement", b =>
                {
                    b.Navigation("DocumentsAttendus");

                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
